### ISSUE TITLE
Windows lib files from prebuilt 6.15.0 are invalid

### ISSUE THREAD

**Issue by ttgil** [firebase/firebase-cpp-sdk#62]
### Environment
Pre-built SDK from the [website](https://firebase.google.com/download/cpp)
Firebase C++ SDK version: 6.15.0
Firebase plugins in use (Auth, Database, etc.): All
Platform you are using the C++ SDK on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): desktop

Compiler: MSVC 2017

### Please describe the issue here:
The 6.15.0 windows libs seem to be invalid.  Linking to them produces an error: warning LNK4003: invalid library format; library ignored.

Opening any of the libs (MD/MT versions and their Debug/Release variants in Dependency Walker shows the error "No DOS or PE signature found.  This file is not a valid 32-bit or 64-bit Windows module."

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ? Haven't tried

What's the issue repro rate?
100%

**Comment by ttgil** [comment]
Update: I'm still seeing link errors with the 6.15.1 release.  The x86 variants report errors about being invalid library files, and the x64 build shows linker errors including: 

`firebase_app.lib(c37549f33e17a87204ce560dbea84583_leveldb_db.dir_Release_dbformat.obj) : error LNK2001: unresolved external symbol "__int64 const std::_BADOFF" (?_BADOFF@std@@3_JB)
firebase_app.lib(b3a3b0b91c57c25221b7ec3e4c3040b3_app.dir_Release_variant_util.obj) : error LNK2001: unresolved external symbol "__int64 const std::_BADOFF" (?_BADOFF@std@@3_JB)
firebase_app.lib(499ef9a09abe9ad8c380c0e2b95f980c_flatbuffers.dir_Release_idl_gen_text.obj) : error LNK2001: unresolved external symbol "__int64 const std::_BADOFF" (?_BADOFF@std@@3_JB)
firebase_app.lib(3869fd1e661ac20f0b7a4d7108455e3d_instance_id_desktop_impl.dir_Release_instance_id_desktop_impl.obj) : error LNK2001: unresolved external symbol "__int64 const std::_BADOFF" (?_BADOFF@std@@3_JB)`

Tried using MSVC2017 and 2019 with the same results.

After googling _BADOFF, found this:

> Thanks for the feedback; but this issue is not a bug. _BADOFF was an STL-internal name for -1 which was unfortunately DLL exported. Its presence arbitrarily prevented even the most basic of optimizations inside iostreams' machinery. Names which are _Leading_underscore_capital_ugly are reserved for the C++ implementation and are not intended to remain consistent between releases, so you shouldn't touch those unless the name is explicitly documented as an extension, such as std::basic_string::_Copy_s. See https://eel.is/c++draft/lex.name#3.1 in the C++ standard.

Can anyone out there confirm if they have managed to get anything that works with 6.15.0 or 6.15.1 on Windows?  Is it just me?

**Comment by ttgil** [comment]
Update: Things seem to be working when I switched from MT to MD library files.  Just leaving everything here in case someone else hits the same problem.

**Comment by guanghui1987** [comment]
I use Windows lib files from prebuilt 6.15.1 are invalid. and the same problem. x86 is not ok, but x64 is ok.
x86\Debug\firebase_auth.lib : warning LNK4003: invalid library format; library ignored
\x86\Debug\firebase_app.lib : warning LNK4003: invalid library format; library ignored

**Comment by chkuang-g** [comment]
@ttgil 

I'm not particularly familiar with std::_BADOFF.  But according to [this post](https://stackoverflow.com/questions/19653749/c-unresolved-external-symbol-when-using-wofstream), the symbol seem to be from MSVCPRT.LIB, which requires `/MD` option.

Invalid x86 library sounds bad.  I'll ping the team to get more info about this.
Shawn

**Comment by chkuang-g** [comment]
Got response from the team

`X86 MT windows is a known issue. Workaround is to switch to MD or build the open source SDK instead`

Hope this helps!

**Comment by cfogelklou** [comment]
Switching to MD did not work for me. Added set(MSVC_RUNTIME_MODE MD) to CMakeLists.txt and also manually edited the MSVC project file for runtime library MD I still get "invalid library format; library ignored."  Using Visual Studio 2015 to match the libraries, too.

**Comment by crazyhappygame** [comment]
The same issue with firebase_cpp_sdk_6.16.1.zip.
Step to reproduce:
1. In visual studio create an empty console project
2. add firebase header and lib to cpp file. For example:
```
#include <iostream>
#include "firebase/app.h"

#pragma comment(lib, "g:/firebase_cpp_sdk/libs/windows/VS2015/MD/x86/Debug/firebase_app.lib")
int main()
{
    std::cout << "Hello World!\n" << firebase::App::Create();
}
```
3. Build
```
1>g:\firebase_cpp_sdk\libs\windows\VS2015\MD\x86\Debug\firebase_app.lib : warning LNK4003: invalid library format; library ignored
1>ConsoleApplication4.obj : error LNK2019: unresolved external symbol "public: static class firebase::App * __cdecl firebase::App::Create(void)" (?Create@App@firebase@@SAPAV12@XZ) referenced in function _main
1>C:\ConsoleApplication4\Debug\ConsoleApplication4.exe : fatal error LNK1120: 1 unresolved externals
```
4. Problem compilation fails

Hints:
0. Please setup CI with the code above to find such problems in advance
1. It looks like the static libraries are incorrect. Please check content in the text editor
```
!<arch>
//                                              40284     `
b86e8e19a0f805269c4ff73c6dcbcb25_app.dir_Debug_uuid.obj/
b86e8e19a0f805269c4ff73c6dcbcb25_app.dir_Debug_locale.obj/
b86e8e19a0f805269c4ff73c6dcbcb25_app.dir_Debug_user_secure_windows_internal.obj/
```
2. It works fine on 6.2.0

**Comment by pbs0512** [comment]
I also have the same problem with firebase_cpp_sdk_6.16.1.zip. I hope it can be resolved as soon as possible.

**Comment by ttgil** [comment]
6+ months on... shouldn't solving release packaging/builds and ensuring the SDK works across all supported platforms be a high priority?  We're betting a lot on building product around the C++ SDK, so would be nice to get an update about what's going on internally.

**Comment by jonsimantov** [comment]
This issue is fixed in release 7.0.0 and later. All Windows prebuilt library variants (Release/Debug, MD/MT, x86/x64) should function normally.

(Note that the minimum supported compiler version on Windows is now Visual Studio 2019. See the [7.0.0 release notes](https://firebase.google.com/support/release-notes/cpp-relnotes#7.0.0) for more information.)
