### ISSUE TITLE
[Bug] Unresolved external symbol error on Windows build with Firebase C++ SDK 12.1.0 and above

### ISSUE THREAD

**Issue by pbs0512** [firebase/firebase-cpp-sdk#1665]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: Pre-built SDK from website
  * Firebase C++ SDK version: 12.1.0 and above
  * Problematic Firebase Component: Firestore
  * Other Firebase Components in use: None
  * Platform you are using the C++ SDK on: Windows
  * Platform you are targeting: desktop

### [REQUIRED] Please describe the issue here:

This issue occurs when building a project on Windows with Firebase C++ SDK versions 12.1.0 and above. The build fails with an unresolved external symbol error linked to the firebase_firestore.lib file.

### Steps to reproduce:
1. Set up a C++ project on Windows.
2. Integrate Firebase C++ SDK (version 12.1.0 or higher) with Firestore as a dependency.
3. Build the project.

Code: LNK2019  
Description: unresolved external symbol ___std_min_8i@8 referenced in function "auto __cdecl std::__std_min<__int64 const >(__int64 const * const,__int64 const * const)" (??$__std_min@$$CB_J@std@@YA?A_PQB_J0@Z)  

Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp)?
No, the issue was reproduced on a custom project using Firestore.

What's the issue repro rate?
100%

I am encountering a persistent linker error when building on Windows with Firebase C++ SDK version 12.1.0 and later. The issue does not appear in version 12.0.0, but it consistently arises in 12.1.0 and above.

Code: LNK2019  
Description: unresolved external symbol ___std_min_8i@8 referenced in function "auto __cdecl std::__std_min<__int64 const >(__int64 const * const,__int64 const * const)" (??$__std_min@$$CB_J@std@@YA?A_PQB_J0@Z)

**Comment by dconeybe** [comment]
I am unable to reproduce. I successfully compiled the Firestore quickstart app on Microsoft Windows Server 2022 (after making a small fix: https://github.com/firebase/quickstart-cpp/pull/147) against Firebase C++ SDK v12.5.0.

Could you provide a project that reproduces the build error? Ideally, this would be a git repository that I can clone and reproduce the build error for myself. The Firestore quickstart app may be a good starting point for this: https://github.com/firebase/quickstart-cpp/tree/main/firestore
